### ISSUE TITLE
500 error with plain curl request

### ISSUE THREAD

**Issue by itorres** [onna/guillotina_prometheus#1]
I would expect  that ` curl localhost:8080/metrics`  gets me a plain text list of metrics. Instead a 500 error is raised:

```
<html><head><title>500 Internal Server Error</title></head><body><h1>500 Internal Server Error</h1>Server got itself in trouble</body></html>
```

And in the error log I get:
```
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 422, in start
    resp = yield from self._request_handler(request)
  File "/usr/local/lib/python3.6/site-packages/guillotina/factory/app.py", line 102, in _handle
    return await super()._handle(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web.py", line 306, in _handle
    resp = yield from handler(request)
  File "/usr/local/lib/python3.6/site-packages/prometheus_async/aio/_decorators.py", line 42, in decorator
    rv = yield from wrapped(*args, **kw)
  File "/usr/local/lib/python3.6/site-packages/guillotina_prometheus/middleware.py", line 9, in middleware_handler
    resp = await handler(request)
  File "/usr/local/lib/python3.6/site-packages/guillotina/traversal.py", line 243, in handler
    resp = await self.rendered(view_result)
  File "/usr/local/lib/python3.6/site-packages/guillotina/renderers.py", line 209, in __call__
    resp = self.guess_response(value)
  File "/usr/local/lib/python3.6/site-packages/guillotina/renderers.py", line 192, in guess_response
    if '<html' in resp:
TypeError: argument of type 'Response' is not iterable
```

**Comment by vangheem** [comment]
Should be fixed with https://github.com/plone/guillotina/commit/d30d6b2a1bd7d7f5673dfb6e11782a2d1fe7ed9d

**Comment by itorres** [comment]
It is fixed. Thanks.
